import { VendorSkill, CHECKOUT_METHOD_LABELS, CAPABILITY_LABELS, computeAgentFriendliness } from "./types";

export function generateVendorSkill(vendor: VendorSkill): string {
  const primaryMethod = vendor.checkoutMethods[0];
  const primaryConfig = primaryMethod ? vendor.methodConfig[primaryMethod] : undefined;
  const friendliness = computeAgentFriendliness(vendor);

  const methodsList = vendor.checkoutMethods
    .map(m => {
      const config = vendor.methodConfig[m];
      const label = CHECKOUT_METHOD_LABELS[m];
      const authNote = config?.requiresAuth ? " (requires login)" : "";
      return `- **${label}**${authNote}${config?.notes ? ` — ${config.notes}` : ""}`;
    })
    .join("\n");

  const capsList = vendor.capabilities
    .map(c => CAPABILITY_LABELS[c])
    .join(", ");

  const tipsSection = vendor.tips.map(t => `- ${t}`).join("\n");

  const searchSection = [
    vendor.search.pattern,
    vendor.search.urlTemplate ? `\nSearch URL: \`${vendor.search.urlTemplate}\`` : "",
    vendor.search.productIdFormat ? `\nProduct ID format: \`${vendor.search.productIdFormat}\`` : "",
  ]
    .filter(Boolean)
    .join("\n");

  const shippingLines = [
    vendor.shipping.freeThreshold
      ? `Free shipping on orders over $${vendor.shipping.freeThreshold}.`
      : "No standard free shipping threshold.",
    `Estimated delivery: ${vendor.shipping.estimatedDays}`,
    vendor.shipping.businessShipping ? "Business/bulk shipping rates available." : "",
  ]
    .filter(Boolean)
    .join("\n");

  const checkoutLines = [
    vendor.checkout.guestCheckout
      ? "Guest checkout is available — no account needed."
      : "Account login required before checkout.",
    vendor.checkout.poNumberField
      ? "- PO number field available at checkout."
      : "",
    vendor.checkout.taxExemptField
      ? "- Tax exemption field available. Check if your owner has a tax certificate on file."
      : "",
  ]
    .filter(Boolean)
    .join("\n");

  const purchaseExample = primaryConfig?.locatorFormat
    ? `
## Making the Purchase

\`\`\`bash
curl -X POST https://creditclaw.com/api/v1/${primaryMethod === "native_api" ? "card-wallet/bot/purchase" : "bot/merchant/checkout"} \\
  -H "Authorization: Bearer $CREDITCLAW_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "merchant": "${vendor.slug}",
    "product_id": "${primaryConfig.locatorFormat}",
    "shipping_address": { "name": "...", "line1": "...", "city": "...", "state": "...", "postalCode": "...", "country": "US" }
  }'
\`\`\`
`
    : "";

  const trackingNote = vendor.capabilities.includes("order_tracking")
    ? "Order tracking is available. Poll the status endpoint for shipping updates."
    : "Order tracking is not yet available for this vendor. Monitor email for shipping confirmation.";

  return `---
name: creditclaw-shop-${vendor.slug}
version: ${vendor.version}
description: "Shop ${vendor.name} using CreditClaw payment rails"
homepage: https://creditclaw.com/skills/${vendor.slug}
requires: [creditclaw]
maturity: ${vendor.maturity}
agent_friendliness: ${friendliness}/5
last_verified: ${vendor.lastVerified}
---

# Shopping at ${vendor.name}

**Store URL:** ${vendor.url}
**Category:** ${vendor.category}
**Agent Friendliness:** ${"★".repeat(friendliness)}${"☆".repeat(5 - friendliness)} (${friendliness}/5)
**Capabilities:** ${capsList}
${vendor.feedbackStats ? `**Success Rate:** ${Math.round(vendor.feedbackStats.successRate * 100)}%` : ""}

---

## Checkout Methods (in order of preference)

${methodsList}

---

## How to Search

${searchSection}

---

## How to Checkout

${checkoutLines}

Use your CreditClaw credentials to pay.
${primaryConfig?.searchEndpoint ? `\nCall \`POST ${primaryConfig.searchEndpoint}\` with the product URL to get variant/pricing info before purchasing.` : ""}

---

## Shipping

${shippingLines}

---

## Tips

${tipsSection}

---
${purchaseExample}
## Tracking

${trackingNote}

---

## Metadata

- **Version:** ${vendor.version}
- **Last verified:** ${vendor.lastVerified}
- **Generated by:** ${vendor.generatedBy}
- **Skill URL:** https://creditclaw.com/api/v1/bot/skills/${vendor.slug}
- **Catalog page:** https://creditclaw.com/skills/${vendor.slug}
`;
}
