import { VendorSkill } from "./types";

export const VENDOR_REGISTRY: VendorSkill[] = [
  {
    slug: "amazon",
    name: "Amazon",
    logoUrl: "/images/vendors/amazon.svg",
    category: "retail",
    url: "https://www.amazon.com",
    checkoutMethods: ["native_api", "self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "programmatic_checkout", "order_tracking", "returns"],
    maturity: "verified",
    methodConfig: {
      native_api: {
        locatorFormat: "amazon:{ASIN}",
        searchEndpoint: "/api/v1/card-wallet/bot/search",
        requiresAuth: false,
        notes: "Full programmatic purchasing via CrossMint. Use ASIN as product identifier.",
      },
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: true,
        notes: "Fallback for items not available through CrossMint API.",
      },
    },
    search: {
      pattern: "Search by product name or paste an ASIN directly. No login needed to browse products and prices.",
      urlTemplate: "https://www.amazon.com/s?k={q}",
      productIdFormat: "ASIN (e.g., B0EXAMPLE123)",
    },
    checkout: { guestCheckout: false, taxExemptField: false, poNumberField: false },
    shipping: { freeThreshold: 35, estimatedDays: "1-5 business days", businessShipping: false },
    tips: [
      "Use ASIN for fastest checkout — no browser interaction needed",
      "CrossMint handles fulfillment end-to-end including tracking",
      "Prime shipping not available through API — standard shipping only",
      "Check product availability before purchasing; some items are marketplace-only",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-15",
    generatedBy: "manual",
    feedbackStats: { successRate: 0.94 },
  },
  {
    slug: "shopify",
    name: "Shopify Stores",
    logoUrl: "/images/vendors/shopify.svg",
    category: "retail",
    url: "https://www.shopify.com",
    checkoutMethods: ["native_api", "self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "programmatic_checkout"],
    maturity: "verified",
    methodConfig: {
      native_api: {
        locatorFormat: "{product_url}:{variant_id}",
        searchEndpoint: "/api/v1/card-wallet/bot/search",
        requiresAuth: false,
        notes: "Variant lookup required before purchase. Use the search endpoint with the product URL.",
      },
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Works with any Shopify store checkout. Guest checkout usually available.",
      },
    },
    search: {
      pattern: "Navigate to the Shopify store URL and search using the store's search bar. Use the CreditClaw search endpoint to look up variant IDs.",
      productIdFormat: "Product URL + Variant ID",
    },
    checkout: { guestCheckout: true, taxExemptField: false, poNumberField: false },
    shipping: { estimatedDays: "Varies by store", businessShipping: false },
    tips: [
      "Always look up variants before purchasing — Shopify products require a specific variant ID",
      "The search API is in beta and may not work for all Shopify stores",
      "No delivery tracking after order is placed through the API",
      "Guest checkout is usually available on most Shopify stores",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-15",
    generatedBy: "manual",
    feedbackStats: { successRate: 0.87 },
  },
  {
    slug: "amazon-business",
    name: "Amazon Business",
    logoUrl: "/images/vendors/amazon-business.svg",
    category: "retail",
    url: "https://business.amazon.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "bulk_pricing", "tax_exemption", "po_numbers", "order_tracking", "business_invoicing", "account_creation"],
    maturity: "beta",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: true,
        notes: "Requires Amazon Business account. Owner must set up account beforehand. Tax exemption certs can be uploaded in account settings.",
      },
    },
    search: {
      pattern: "Search normally on business.amazon.com. Look for 'Business Price' and 'Quantity Discounts' badges for bulk pricing.",
      urlTemplate: "https://www.amazon.com/s?k={q}",
      productIdFormat: "ASIN",
    },
    checkout: { guestCheckout: false, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: 25, estimatedDays: "1-5 business days", businessShipping: true },
    tips: [
      "Requires Amazon Business account — owner must set up beforehand",
      "Tax exemption certificates can be uploaded in account settings",
      "Quantity discounts often beat consumer Amazon by 15-40%",
      "PO numbers can be attached to orders for accounting",
      "Business Prime offers free shipping on all orders",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-10",
    generatedBy: "manual",
  },
  {
    slug: "walmart",
    name: "Walmart",
    logoUrl: "/images/vendors/walmart.svg",
    category: "retail",
    url: "https://www.walmart.com",
    checkoutMethods: ["self_hosted_card", "browser_automation"],
    capabilities: ["price_lookup", "stock_check", "order_tracking"],
    maturity: "beta",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. Standard credit card checkout flow.",
      },
      browser_automation: {
        requiresAuth: false,
        notes: "Fallback for complex product configurations or marketplace items.",
      },
    },
    search: {
      pattern: "Search on walmart.com. Products are identified by item number in the URL. Filter by price, rating, and availability.",
      urlTemplate: "https://www.walmart.com/search?q={q}",
      productIdFormat: "Item number (numeric, found in URL)",
    },
    checkout: { guestCheckout: true, taxExemptField: false, poNumberField: false },
    shipping: { freeThreshold: 35, estimatedDays: "2-7 business days", businessShipping: false },
    tips: [
      "Guest checkout is available — no account needed for basic purchases",
      "Walmart+ members get free shipping on all orders",
      "Marketplace items may have different shipping policies",
      "In-store pickup available for many items (not supported via API yet)",
      "Price matching is not available for online orders",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-10",
    generatedBy: "manual",
  },
  {
    slug: "walmart-business",
    name: "Walmart Business",
    logoUrl: "/images/vendors/walmart-business.svg",
    category: "retail",
    url: "https://business.walmart.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "bulk_pricing", "tax_exemption", "po_numbers", "business_invoicing", "account_creation"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: true,
        notes: "Requires Walmart Business account. Supports tax exemption and purchase orders.",
      },
    },
    search: {
      pattern: "Search on business.walmart.com. Look for bulk pricing tiers and business-specific products.",
      urlTemplate: "https://business.walmart.com/search?q={q}",
      productIdFormat: "Item number",
    },
    checkout: { guestCheckout: false, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: 35, estimatedDays: "2-7 business days", businessShipping: true },
    tips: [
      "Requires Walmart Business account — owner must register first",
      "Tax exemption available after uploading certificates",
      "Bulk pricing available on qualifying quantities",
      "Business+ membership includes free shipping and 2% rewards",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-08",
    generatedBy: "manual",
  },
  {
    slug: "staples",
    name: "Staples",
    logoUrl: "/images/vendors/staples.svg",
    category: "office",
    url: "https://www.staples.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "bulk_pricing", "tax_exemption", "po_numbers", "order_tracking", "business_invoicing"],
    maturity: "beta",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available for basic orders. Business account needed for PO numbers and tax exemption.",
      },
    },
    search: {
      pattern: "Search on staples.com by product name or SKU. Filter by brand, price, and availability. Check for Staples Advantage pricing on business accounts.",
      urlTemplate: "https://www.staples.com/search?query={q}",
      productIdFormat: "SKU / Item number",
    },
    checkout: { guestCheckout: true, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: 49.99, estimatedDays: "1-5 business days", businessShipping: true },
    tips: [
      "Guest checkout available but business accounts get better pricing",
      "Staples Advantage (business tier) offers volume discounts",
      "Free next-day delivery on orders over $49.99 in eligible areas",
      "Tax exemption requires a Staples business account with certificate on file",
      "Weekly deals and coupons can significantly reduce costs",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-10",
    generatedBy: "manual",
  },
  {
    slug: "home-depot",
    name: "Home Depot",
    logoUrl: "/images/vendors/home-depot.svg",
    category: "hardware",
    url: "https://www.homedepot.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "order_tracking", "bulk_pricing"],
    maturity: "beta",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. Product pages show real-time store and online inventory.",
      },
    },
    search: {
      pattern: "Search on homedepot.com by product name, brand, or model number. Products show real-time stock levels for both online and nearby stores.",
      urlTemplate: "https://www.homedepot.com/s/{q}",
      productIdFormat: "Internet # or Model # (found on product page)",
    },
    checkout: { guestCheckout: true, taxExemptField: false, poNumberField: false },
    shipping: { freeThreshold: 45, estimatedDays: "3-7 business days", businessShipping: false },
    tips: [
      "Guest checkout works for standard online orders",
      "Product pages show real-time local store inventory",
      "Pro Xtra accounts offer volume pricing on qualifying orders",
      "Some items are 'ship to store' only and cannot be delivered",
      "Large/heavy items may incur additional shipping charges",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-10",
    generatedBy: "manual",
  },
  {
    slug: "lowes",
    name: "Lowe's",
    logoUrl: "/images/vendors/lowes.svg",
    category: "hardware",
    url: "https://www.lowes.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "order_tracking"],
    maturity: "beta",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. Similar to Home Depot flow.",
      },
    },
    search: {
      pattern: "Search on lowes.com by product name or item number. Filter by brand, price, rating, and availability.",
      urlTemplate: "https://www.lowes.com/search?searchTerm={q}",
      productIdFormat: "Item # or Model # (found on product page)",
    },
    checkout: { guestCheckout: true, taxExemptField: false, poNumberField: false },
    shipping: { freeThreshold: 45, estimatedDays: "3-7 business days", businessShipping: false },
    tips: [
      "Guest checkout is straightforward",
      "Lowe's Pro accounts get volume pricing and dedicated support",
      "Price match guarantee — matches competitor pricing including Amazon",
      "Some items available for same-day delivery in select markets",
      "Bulk/pallet orders may require calling the pro desk",
    ],
    version: "1.0.0",
    lastVerified: "2026-02-10",
    generatedBy: "manual",
  },
  {
    slug: "office-depot",
    name: "Office Depot",
    logoUrl: "/images/vendors/office-depot.svg",
    category: "office",
    url: "https://www.officedepot.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "tax_exemption", "po_numbers", "order_tracking", "business_invoicing"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. Business accounts unlock tax exemption and PO numbers.",
      },
    },
    search: {
      pattern: "Search on officedepot.com by product name, SKU, or brand. Filter by category and price.",
      urlTemplate: "https://www.officedepot.com/catalog/search.do?Ntt={q}",
      productIdFormat: "SKU / Item number",
    },
    checkout: { guestCheckout: true, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: 45, estimatedDays: "2-5 business days", businessShipping: true },
    tips: [
      "Guest checkout for basic orders, business account for invoicing features",
      "BSD (Business Solutions Division) accounts get contract pricing",
      "Free next-business-day delivery on qualifying orders",
      "Price match available on identical items from select competitors",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
  {
    slug: "uline",
    name: "Uline",
    logoUrl: "/images/vendors/uline.svg",
    category: "industrial",
    url: "https://www.uline.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "bulk_pricing", "order_tracking", "business_invoicing", "po_numbers"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Phone orders also accepted. Website checkout is straightforward.",
      },
    },
    search: {
      pattern: "Search on uline.com by product name or model number. Uline's catalog is extremely deep for shipping, packaging, and industrial supplies.",
      urlTemplate: "https://www.uline.com/BL/Search?keywords={q}",
      productIdFormat: "Model # (e.g., S-12345)",
    },
    checkout: { guestCheckout: true, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: undefined, estimatedDays: "1-2 business days (ships from nearest warehouse)", businessShipping: true },
    tips: [
      "Ships from the nearest of 13 US warehouses — typically arrives in 1-2 days",
      "Quantity pricing breaks are clearly shown on product pages",
      "Net 30 terms available for established business accounts",
      "Catalog is strongest for shipping, packaging, janitorial, and warehouse supplies",
      "Free catalog available by request — useful for product discovery",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
  {
    slug: "grainger",
    name: "Grainger",
    logoUrl: "/images/vendors/grainger.svg",
    category: "industrial",
    url: "https://www.grainger.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "bulk_pricing", "tax_exemption", "po_numbers", "order_tracking", "business_invoicing", "account_creation"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: true,
        notes: "Account required for pricing. Guest browsing shows 'Sign in for price' on many items.",
      },
    },
    search: {
      pattern: "Search on grainger.com by product name, brand, or Grainger item number. Many prices require login to view.",
      urlTemplate: "https://www.grainger.com/search?searchQuery={q}",
      productIdFormat: "Grainger Item # (e.g., 6YA12)",
    },
    checkout: { guestCheckout: false, taxExemptField: true, poNumberField: true },
    shipping: { freeThreshold: undefined, estimatedDays: "1-3 business days", businessShipping: true },
    tips: [
      "Account required to see contract pricing — owner must set up beforehand",
      "One of the largest MRO (maintenance, repair, operations) suppliers",
      "Net 30/60/90 terms available for qualified business accounts",
      "Same-day shipping on most in-stock items ordered by noon local time",
      "Product specs and safety data sheets available on every product page",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
  {
    slug: "newegg",
    name: "Newegg",
    logoUrl: "/images/vendors/newegg.svg",
    category: "electronics",
    url: "https://www.newegg.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "order_tracking", "returns"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. Strong for computer components and electronics.",
      },
    },
    search: {
      pattern: "Search on newegg.com by product name, brand, or model number. Excellent filtering by specs (CPU socket, RAM type, etc.).",
      urlTemplate: "https://www.newegg.com/p/pl?d={q}",
      productIdFormat: "Newegg Item # (e.g., N82E16835856145)",
    },
    checkout: { guestCheckout: true, taxExemptField: false, poNumberField: false },
    shipping: { freeThreshold: undefined, estimatedDays: "3-7 business days", businessShipping: false },
    tips: [
      "Best for computer components, peripherals, and consumer electronics",
      "Shell Shocker and daily deals can offer significant discounts",
      "Newegg Business available for tax-exempt and volume purchasing",
      "Marketplace sellers may have different return policies than Newegg direct",
      "Combo deals bundle related items at a discount",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
  {
    slug: "bh-photo",
    name: "B&H Photo",
    logoUrl: "/images/vendors/bh-photo.svg",
    category: "electronics",
    url: "https://www.bhphotovideo.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "order_tracking", "tax_exemption", "returns"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: false,
        notes: "Guest checkout available. No sales tax on orders shipped outside NY.",
      },
    },
    search: {
      pattern: "Search on bhphotovideo.com by product name, brand, or B&H item number. Detailed spec filtering available.",
      urlTemplate: "https://www.bhphotovideo.com/c/search?q={q}",
      productIdFormat: "B&H # (e.g., CANR5)",
    },
    checkout: { guestCheckout: true, taxExemptField: true, poNumberField: false },
    shipping: { freeThreshold: 49, estimatedDays: "2-7 business days", businessShipping: false },
    tips: [
      "No sales tax on most orders shipped outside New York state",
      "Excellent for cameras, audio equipment, lighting, and pro video gear",
      "Used/refurbished section offers significant savings",
      "Closed on Saturdays and Jewish holidays — orders placed during these times ship the next business day",
      "Free expedited shipping on many items over $49",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
  {
    slug: "mcmaster-carr",
    name: "McMaster-Carr",
    logoUrl: "/images/vendors/mcmaster-carr.svg",
    category: "industrial",
    url: "https://www.mcmaster.com",
    checkoutMethods: ["self_hosted_card"],
    capabilities: ["price_lookup", "stock_check", "order_tracking", "bulk_pricing"],
    maturity: "draft",
    methodConfig: {
      self_hosted_card: {
        locatorFormat: "url:{product_url}",
        requiresAuth: true,
        notes: "Account required. McMaster-Carr is notoriously difficult to browse without an account.",
      },
    },
    search: {
      pattern: "Search on mcmaster.com by product description or McMaster part number. The site uses a proprietary navigation system — no standard URL-based search.",
      productIdFormat: "McMaster Part # (e.g., 91251A545)",
    },
    checkout: { guestCheckout: false, taxExemptField: true, poNumberField: true },
    shipping: { estimatedDays: "Next day (most items)", businessShipping: true },
    tips: [
      "Account required — owner must register before bot can purchase",
      "Fastest shipping in industrial supply — most items arrive next day",
      "The definitive source for fasteners, raw materials, and industrial components",
      "No price matching or negotiation — prices are fixed",
      "CAD models available for most products",
    ],
    version: "0.1.0",
    lastVerified: "2026-02-05",
    generatedBy: "manual",
  },
];

export function getVendorBySlug(slug: string): VendorSkill | undefined {
  return VENDOR_REGISTRY.find(v => v.slug === slug);
}

export function getVendorsByCategory(category: string): VendorSkill[] {
  return VENDOR_REGISTRY.filter(v => v.category === category);
}

export function searchVendors(query: string): VendorSkill[] {
  const q = query.toLowerCase();
  return VENDOR_REGISTRY.filter(
    v => v.name.toLowerCase().includes(q) || v.slug.includes(q) || v.category.includes(q)
  );
}
